### ISSUE TITLE
Bad gif can cause massive memory usage and cpu haulting

### ISSUE THREAD

**Issue by strazzere** [kohler/gifsicle#100]
While doing some fuzzing I ran into some odd instances where some specifically crafted gifs

![image](https://user-images.githubusercontent.com/623686/27457711-90351d82-575a-11e7-999c-0eb3c1aa4172.png)

```
rigby:gifsicle diff$ ls -lh crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2
-rw-------  1 diff  staff   332B Mar  2 13:21 crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2
rigby:gifsicle diff$ ./src/gifsicle -O2 crashes/loops/id\:000075\,orig\:id\:000204\,src\:002229\,op\:havoc\,rep\:2 --output /dev/null
gifsicle: warning: huge GIF, conserving memory (processing may take a while)
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2:#6: read error: image corrupted, min_code_size too big
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2:#6: read error: missing 64 pixels of image data
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2:#7: read error: image corrupted, min_code_size too big
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2:#7: read error: missing 64 pixels of image data
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2:#8: read error: image corrupted, min_code_size too big
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2:#8: read error: missing 15602876 pixels of image data
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2:#0: read error: image corrupted, min_code_size too big
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2:#0: read error: missing 44 pixels of image data
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2: warning: some colors undefined by colormap
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2:#1: read error: image corrupted, min_code_size too big
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2:#1: read error: missing 140 pixels of image data
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2: warning: some colors undefined by colormap
gifsicle: (plus more errors; is this GIF corrupt?)
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2: warning: some colors undefined by colormap
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2: warning: some colors undefined by colormap
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2: warning: some colors undefined by colormap
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2: warning: some colors undefined by colormap
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2: warning: some colors undefined by colormap
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2: warning: some colors undefined by colormap
gifsicle:crashes/loops/id:000075,orig:id:000204,src:002229,op:havoc,rep:2: warning: some colors undefined by colormap
```

As you can see the file is < 332B and depending on the machine - can quickly hog upwards of 25gb of memory. Sadly I have not had time to dig into what part of the code is causing this usage. If I have time in the future to combine it with c-reduce, I'll follow up here.

Attached is one of the files which can cause this condition;
[memory-hog.zip](https://github.com/kohler/gifsicle/files/1096283/memory-hog.zip)

**Comment by kohler** [comment]
This gif claims to be 65295x11775 pixels large. That is very large, and large memory usage when optimizing such images is expected behavior. (gifsicle optimization involves at least 4 image-size arrays, where here an image has ~770 megapixels.)

**Comment by strazzere** [comment]
Sure, I understand the image is claiming to that size - would just seem like a potentially good idea to step into the image and check if those pixels actually exist, no?

**Comment by kohler** [comment]
Why. They could easily exist (it would be easy to construct a gif that had the same boundaries but was valid). Are you proposing to make gifsicle more robust against fuzzing, or what? Making gifsicle more robust against fuzzing does not seem like a good use of time. Making gifsicle optimization use a fixed amount of memory regardless of input image size might be more broadly applicable but it would also take a lot of work.

**Comment by kohler** [comment]
I should also note that it is gifsicle policy to attempt to muddle on when presented with a partially-invalid gif, such as this one. Segfaults, undefined behavior are bugs, this just isn't.

**Comment by strazzere** [comment]
*shrug* it's up to you. Seems like a bad idea to allow an optimizer to consume that much memory if it comes across a corrupt gif. Unsure if other people use this application in any production services, though this would not perform "nicely" if it is running alongside any other services.

**Comment by kohler** [comment]
Gifsicle is used in production, yes.

**Comment by saurabheights** [comment]
@strazzere: Hi, I just noticed this issue, so please forgive this late communication. You can selectively reduce such issues by reading image metadata beforehand and filtering such cases. Metadata-extractor(Java) and ExifTool(bash/Perl) will be good here for reading only metadata. By the way, the attached file was not a GIF file. On running `xxd hog-memory.gif` there is no GIF87a or GIF89a as the first 6 bytes. Please check the file hex dump, it is corrupt as Kohler mentioned.
