### ISSUE TITLE
fcntl.h

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [kohler/gifsicle#110]
Using _setmode in Visual C++ requieres including fcntl.h, so that should be added in the source.

**Comment by h3xx** [comment]
Can you elaborate? Please post any error messages you are receiving when compiling in your environment.

**Comment by javiergutierrezchamorro** [comment]
The thing is that fcntl.h shall be included in any file that uses _setmode. Reason is that _O_BINARY is defined in that header file under Visual C++:
https://docs.microsoft.com/cpp/c-runtime-library/reference/setmode

**Comment by kohler** [comment]
That file is in fact `#include`d in `win32cfg.h`.
