### ISSUE TITLE
read error(unknown block type, image corrupted)

### ISSUE THREAD

**Issue by cocoakekeyu** [kohler/gifsicle#112]
source: http://cdn.fatu.me/Fk7mgHZVZGENQX-DRKPD9Ehnbq3t

here is gifsicle output:

![image](https://user-images.githubusercontent.com/4177398/28448318-b7de8a24-6e09-11e7-9561-e1b775eb3df4.png)

the out.gif file is wrong, why output? 

gifsicle print some warning and actual output right file, but return value is -1.  #89

**Comment by mdiller** [comment]
I am also getting a similar error about an unknown block type, and it results in gifsicle cutting the animation off very early.
`$ gifsicle --optimize lanes.gif -o out.gif
gifsicle: While reading 'lanes.gif' frame #151:
gifsicle:   error: unknown block type 0 at file offset 8486972
gifsicle: warning: so many colors that local colormaps were required
gifsicle: (You may want to try '--colors 256'.)`

gif: https://imgur.com/a/1ufzx

**Comment by h3xx** [comment]
Confirmed using f1b8e6323a8fdd029847b7efd400d5fc2ac9aecc on Linux x86_64.

Furthermore, running `gifsicle --optimize=3 -o out.gif test.gif` causes system memory exhaustion after producing the same error message above.

**Comment by PlNG** [comment]
Issue source image is no longer available - host is gone.
Please try testing the image with [badpeggy](https://www.coderslagoon.com/#/product/badpeggy) and see what that says, if you still have the source image.

**Comment by cocoakekeyu** [comment]
Yes, host is gone.

You can use this visit。

http://oi5s980qg.bkt.clouddn.com/Fk7mgHZVZGENQX-DRKPD9Ehnbq3t

**Comment by kohler** [comment]
This image has 585,624 consecutive zero bytes starting at offset 0x1da2c8. That's certainly corruption. Gifsicle should have given up on the image rather than trying to continue.

**Comment by cocoakekeyu** [comment]
OK， Let it go
