### ISSUE TITLE
ImageMagick 'invalid colormap index' error when reading gifs made with gifsicle

### ISSUE THREAD

**Issue by cyburgee** [kohler/gifsicle#113]
Not certain if this is bug with gifsicle or imagemagick, but after upgrading to imagemagick version 7, attempting to read or resize many animated gifs created with gifsicle result in an 'invalid colormap index' error from imagemagick.

Here's a sample file: https://www.dropbox.com/s/0qc5c5kt7js78f4/original.gif?dl=0

```bash
$ convert -version
Version: ImageMagick 7.0.6-1 Q8 x86_64 2017-07-18 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules 
Delegates (built-in): bzlib fftw fontconfig freetype jng jpeg ltdl lzma png tiff x xml zlib
$
$ gifsicle --version
LCDF Gifsicle 1.89
Copyright (C) 1997-2017 Eddie Kohler
This is free software; see the source for copying conditions.
There is NO warranty, not even for merchantability or fitness for a
particular purpose.
$
$ gifsicle -U original.gif --resize _x100 -O2 > test_100.gif
$
$ convert test_100.gif -coalesce -resize x50 -layers optimize test_50_im.gif
convert: invalid colormap index `test_100.gif' @ error/colormap-private.h/ConstrainColormapIndex/34.
```

I asked the IM developers here and got this response:
```
Both IMv6 and IMv7 detect an invalid colormap index. The colormap has 32 colors and the 
colormap index is 32 which suggests a corrupt image file or ImageMagick is not reading it 
correctly. IMv6 detects the problem but does not report it. We'll add a patch so it does 
report the problem.
```

It may have something to do with transparency optimization in gifsicle and the index used for the transparent color in the colormap, as running the gifsicle command above with the optimization flag set to `-O1` does not cause this error for this particular gif, but it does occur with `-O2` or `-O3` set.

**Comment by kohler** [comment]
IM is incorrect here and I prefer that Gifsicle’s optimization stand. A transparent color **isn’t really in the colormap**: the color value doesn’t matter. I have seen this optimization in GIFs produced by other tools as well.

It would be a bug if Gifsicle generated a **non-transparent** color index that wasn't in the colormap (unless, of course, that happened in the input image too).

Suggest you report this to the IM devs.

**Comment by cyburgee** [comment]
I brought it up with the IM devs and they have committed a fix.
The relevant discussion is here:
https://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=32407

I'll have to do more testing with the fix they implemented but I think this can be closed.

Thanks for your input
