### ISSUE TITLE
Convert non-gifs to gifs?

### ISSUE THREAD

**Issue by hugovk** [kohler/gifsicle#12]
Would it be difficult or worthwhile to allow some non-gifs such as jpg or png as input and convert them to gif first? 

So:

`gifsicle --delay=10 --loop *.jpg > anim.gif`

**Comment by cpitclaudel** [comment]
Do these ImageMagick based solutions actually produce good quality results? Converting to individual gif frames and then assembling them sounds like it would cause a significant quality loss; doesn't it?

**Comment by CyberShadow** [comment]
> Converting to individual gif frames and then assembling them sounds like it would cause a significant quality loss; doesn't it?

That's correct. Each frame would be dithered individually, which removes a lot of information a tool such as gifsicle could use for optimizing successive frames. High-quality GIFs from true color sources is probably outside gifsicle's scope.

**Comment by cpitclaudel** [comment]
I see; thanks for the clarification!

**Comment by chocmake** [comment]
A pity this was closed early as it's a useful suggestion and as mentioned above pre-converting to GIF frames using ImageMagick appears to have its own drawbacks. Assumed gifsicle actually had this feature given all the frame selection options until I found this issue, as was needing to achieve optimized frame to GIF conversion.
