### ISSUE TITLE
For animated gifs: gifsicle sets Photoshops SaveForWeb parameter "lossy" to 60 that cannot be changed. 

### ISSUE THREAD

**Issue by Cyril0001** [kohler/gifsicle#120]
All my animated Gifs start to apear in a very poor quality after gifsicle. Exactly as if you set in Export Option - SaveForWeb - parameter "lossy" to 60. I cannot fight that. Nothing helps so far. Would be very grateful for any help!

**Comment by kohler** [comment]
Post a GIF that looks good; the command line you use to run gifsicle; and the result of running gifsicle.

**Comment by Cyril0001** [comment]
That is how the saved file looks now:
![5303](https://user-images.githubusercontent.com/30271055/33556274-5a90429c-d914-11e7-809c-f9219a8bf848.gif)

That is as it used to be:
![5355](https://user-images.githubusercontent.com/30271055/33556279-603f5d0e-d914-11e7-82bc-aa0fe7404032.gif)

I use the script to batch save animgifs from photoshop. Nothing change, as to my current knowladge :) Here it is.


#target photoshop;  
try{  
var Path= activeDocument.path;  
}catch(e){var Path = "~/desktop";}  
var Name = decodeURI(app.activeDocument.name).replace(/\.[^\.]+$/, '');  
var layerName = app.activeDocument.activeLayer.name.replace(/[:\/\\*\?\"\<\>\|]/g, "_");  
var saveFile= new File(Path + "/" + Name + "-" + layerName + ".gif");  
var rex = new RegExp(Name + "-" + layerName + ".gif");  
var files = decodeURI(saveFile.fsName).replace(rex,"*.gif");  
var cmd = 'D:/gifsicle.exe --batch --loop=forever --careful ';  
cmd += '\"' + files+ '\"';  
SaveForWeb(saveFile);  
app.system(cmd);  
function SaveForWeb(saveFile) {  
var sfwOptions = new ExportOptionsSaveForWeb();  
   sfwOptions.format = SaveDocumentType.COMPUSERVEGIF;  
   sfwOptions.includeProfile = false;  
   sfwOptions.interlaced = 0;  
   sfwOptions.optimized = true;  
   sfwOptions.transparency = 1;  
   sfwOptions.ColorReductionType = ColorReductionType.SELECTIVE;  
   sfwOptions.dither = Dither.NONE;    
   sfwOptions.ditherAmount = 80;  
   sfwOptions.lossy = 8;   
   sfwOptions.webSnap = 0;  
   sfwOptions.colors = 256;  
activeDocument.exportDocument(saveFile, ExportType.SAVEFORWEB, sfwOptions);  
};

**Comment by Cyril0001** [comment]
That is as it used to be:
![5355](https://user-images.githubusercontent.com/30271055/33556483-2646f610-d915-11e7-9908-16eeedb217f8.gif)

**Comment by kohler** [comment]
Running `gifsicle --loop=forever` on your input GIF produces an indistinguishable output GIF.

Most likely the problem is in your SaveForWeb function, which is doing a number of things, including reducing colors.

Bug reports are only accepted here that concern gifsicle; we can't debug your photoshop batch script. Good luck.
