### ISSUE TITLE
Windows Installer

### ISSUE THREAD

**Issue by doakey3** [kohler/gifsicle#128]
I am wondering if you plan to create a Windows Installer. 

Currently I only see binary packages, but an installer that sets the system path so that `gifsicle` can be used from the command line without typing out the path to the executable would be very helpful.

**Comment by kohler** [comment]
I don’t support Windows.

**Comment by doakey3** [comment]
The [website](https://www.lcdf.org/gifsicle/) has a link to [Windows ports](https://eternallybored.org/misc/gifsicle/) supported by Jernej Simončič. Is there a way to get into contact with Mr. Simončič and ask him?

**Comment by jernejs** [comment]
I've got no plans for installer for gifsicle - it's a command-line tool, and in my experience most users of such tools just extract them directly to a directory that's already in PATH.
