### ISSUE TITLE
support plain-text extension?

### ISSUE THREAD

**Issue by jedahan** [kohler/gifsicle#129]
If even just to print out any plain text data on the commandline using `gifsicle -I`, it would be cool to support the plain text extension

**Comment by h3xx** [comment]
What do you mean by "plain text extension"?

Do you mean outputting to a plaintext file? Use `gifsicle -I MYFILE.gif >info.txt`

Do you mean displaying text data from a plaintext file? Use `cat MYFILE.txt`

**Comment by jedahan** [comment]
from https://www.w3.org/Graphics/GIF/spec-gif89a.txt page 18 "Plain Text Extension"
```
