### ISSUE TITLE
--resize-fit should return maximal image which fits in given rectangle

### ISSUE THREAD

**Issue by kgs** [kohler/gifsicle#13]
I have image f.gif (253x288), when I call:

gifsicle --resize-fit 100x200 f.gif -o res.gif

I get image res.gif (100x114), but I should get 176x200. Am I missing something?

PS: f.gif is here http://i.imgur.com/VZzWP1N.gif (253x288)

**Comment by papandreou** [comment]
I cannot get that trick to work:

```
$ gifsicle --version
LCDF Gifsicle 1.86
$ curl -s0 gofish.dk/animated.gif | gifsicle --resize-fit 100x100 --no-logical-screen | gifsicle -I
* <stdin> 3 images
  logical screen 23x20
  global color table [4]
  background 0
  loop forever
  + image #0 23x20
    comment http://www.rtlsoft.com/animagic\n\nCreated with Animagic GIF V 1.06b\nby Right to Left Software Inc.\n\nTo suppress this message in the registered version\nuncheck "Options | Animagic comment frame"\n
    delay 0.01s
  + image #1 23x20
    delay 0.01s
  + image #2 23x20
    delay 0.01s
```

I expected the above to produce a 100x87 gif as that's the maximum size that'll fit within the bounding box. I can see the utility of having two modes ("shrink if necessary to fit within the box" vs. "shrink or enlarge so at least one of the dimensions is equal to that of the box") How about adding a "without enlargement" switch like http://sharp.dimens.io/en/stable/api/#withoutenlargement ?
