### ISSUE TITLE
gifsicle can't run resize or scale command

### ISSUE THREAD

**Issue by iceghosttth** [kohler/gifsicle#132]
I have an animated gif like this
![image](https://user-images.githubusercontent.com/40488299/41768143-9fbc447e-7635-11e8-9733-96591e318eb2.gif)
I want to resize it using the command
`gifsicle --resize _x50 image.gif > image_resized.gif`
But a window popped out and said "gifsicle.exe has stopped working"
Other commands worked fine except this one (and scale). What did i do wrong?

**UPDATE**: Now I can resize with --resize-method sample. I wonder why other resize methods don't work?

**Comment by iceghosttth** [comment]
I downloaded the prebuild version for Window 32bit on the homepage. `gifsicle --version` yields this
![image](https://user-images.githubusercontent.com/40488299/41805659-d07e10bc-76d8-11e8-8a47-e24e74d68c2f.png)

**Comment by h3xx** [comment]
Retried using version 8a9125273aa4f86f55a6c50c0d3baaac6a9e8076 (tag `v1.89`). I was unable to reproduce the crash (full shell history: https://gist.github.com/a1816cf81af2d6e7447662b97b565e2c).
    
Can you reproduce the crash with a newer version of gifsicle, preferably master@HEAD? IIRC there were a bunch of security issues related to crashes were recently fixed.

**Comment by kohler** [comment]
I'm going to close this as not relevant for the current version.
