### ISSUE TITLE
Build gifsicle statically

### ISSUE THREAD

**Issue by matjazu** [kohler/gifsicle#133]
I tried to build binary statically, so that it would not be distro specific, but can not manage to do it properly.

Currently, I tried:
`./configure --disable-gifview --disable-gifdiff`
`make`

However, when I check (`ldd ./src/gifsicle`) for dynamically linked libs, I still get:
`linux-vdso.so.1 (0x00007fffefffe000)`
`libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f91dfefe000)`
`libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f91dfbfa000)`
`libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f91df85b000)`
`/lib64/ld-linux-x86-64.so.2 (0x00007f91e034a000)`

Does anybody have any idea, how can I get above dependencies statically linked?

**Comment by Nyoroon** [comment]
You should build it with musl instead of glibc. Glibc doesn't support full static builds.

**Comment by manfredsc** [comment]
try with
`CC="gcc -static" ./configure; make`
