### ISSUE TITLE
Add --max-colors

### ISSUE THREAD

**Issue by groseler** [kohler/gifsicle#136]
It would be nice to have the option --max-colors=X ir order to only be applied to the ones that have more than X.
Thank you

**Comment by kohler** [comment]
That is how `-k` behaves. Are you referring to the warning that is sometimes printed?

**Comment by groseler** [comment]
Hi Kohler, thank you for the fast response. Love this tool. Yes because of the warning. I didn't notice that the --colors behave like that.  Since this is already the behave I will close this thread.
