### ISSUE TITLE
Binaries updated only for windows but not for other OS

### ISSUE THREAD

**Issue by vsanse** [kohler/gifsicle#137]
Hi @kohler/@kornelski  , I don't mean to be a pest, but any chance we can get binaries for other OS say mac or unix etc. As a lot of npm packages like gifsicle-bin, imagemin-gifsicle depends on it to provide support for --`lossy`.

**Comment by kohler** [comment]
I got out of the business of providing binaries some time ago.

**Comment by Jeremboo** [comment]
Hi @vsanse

Do you find any solutions to make it work on OSX? :(

I also want to use `imagemin-gifsicle`...
