### ISSUE TITLE
Can't compile with multi-threading support on macOS

### ISSUE THREAD

**Issue by vegerot** [kohler/gifsicle#141]
I am confused how exactly to go about enable multi-threaded support.  `./configure --help` mentions an option to _disable_ threads, but does not mention how to turn it on.  Just using regular `./configure; make install` and trying `-j8` seems to still only use 1 thread, which makes me thing it's not actually enabled.
Also, `./configure --enable-threads` doesn't seem to do anything either

**Comment by kohler** [comment]
I'm pretty sure multithreading works on macos. It is only used for certain operations, specifically resizing non-optimized images.
