### ISSUE TITLE
Python wrapper

### ISSUE THREAD

**Issue by LucaCappelletti94** [kohler/gifsicle#142]
Hello,

I wanted to ask if there is already a python wrapper for the library in the making, otherwise I could make one.

Please do let me know how should I proceed,
Luca

**Comment by kohler** [comment]
I don't know of one.

**Comment by LucaCappelletti94** [comment]
Ok, so I'll create one. Is there a complete list of all the library functions and options? As per the documentation, there's just the man page right?

**Comment by LucaCappelletti94** [comment]
Here you go: [pygifsicle on pip](https://pypi.org/project/pygifsicle/1.0.0/) and on [github](https://github.com/LucaCappelletti94/pygifsicle). I've wrapped the library and created just a small method for optimizing gifs, which is what I needed. 

The wrapper is tested on [travis with MacOs and Linux](https://travis-ci.org/LucaCappelletti94/pygifsicle), and the python setup guides the user to install the Gifsicle library.

Thank you for creating this library, it will be extremely helpful for the visualization tool I'm working on.
