### ISSUE TITLE
Libgif error on gifsicle resized file, 

### ISSUE THREAD

**Issue by mudhoney** [kohler/gifsicle#145]
Hi , 

I am working on a service that resizes gifs with gifsicle. Through my tests , gifsicle works great so far, but I have this particular image that is giving me problem.

Normally when I resize it with gifsicle , there is no error , and I can visually validate it is correctly 
resizing the image and the animation is working fine on my ubuntu machine.

But when I try to check the same file on macos , it is very weird that it is slow and animation stops after a while.

I don't know this is related to gifsicle but if I test the original file ( not resized with gifsicle ) 
animation works without any problem.

So I wondered and tried to play with the result file and saw that one of the `giftools` is giving error like `GIF-LIB error: Image EOF detected before image complete.` . I think error comes directly from 
`libgif` . I am using latest released version `1.92`  of gifsicle.

Here is the command that I am executing to generate the problem
```
root@efd81c1062e9:/u/apps/site# gifsicle --resize="201x202" -o - original.gif  | gif2rgb -v

gif2rgb: Image 1 at (0, 0) [201x202]: 201 
gif2rgb: Image 2 at (2, 6) [196x190]: 189 
gif2rgb: Image 3 at (3, 6) [194x190]: 189 GIF-LIB error: Image EOF detected before image complete.
```

I am attaching the problem gif file. Can you help me to understand what is wrong with the resizing operation or there is nothing wrong with it. 

Thanks !!!

### original.gif

![original](https://user-images.githubusercontent.com/1138866/68692343-5548bf00-0543-11ea-8f7b-afb82a341fb6.gif)

**Comment by stalkerg** [comment]
I have the same issue but the EOF error I found in the gif2webp tool.

**Comment by kohler** [comment]
FWIW, I cannot replicate this. Please reopen if you have had more trouble.

**Comment by stalkerg** [comment]
@kohler it fixed in the latest giflib
