### ISSUE TITLE
gifsicle pre-build test failed

### ISSUE THREAD

**Issue by xianghongai** [kohler/gifsicle#151]
Windows 10 64 bit,
Node: v12.16.0
NPM: 6.13.4
Yarn: 1.22.0
Create-React-App: 3.4.0

```bash
[4/4] Building fresh packages...
[-/6] ⠠ waiting...                                                                                                                                                      [6/6] ⠠ optipng-bin                                                                                                                                                     [-/6] ⠐ waiting...                                                                                                                                                      [4/6] ⠐ gifsicle                                                                                                                                                        error D:\ctms\node_modules\gifsicle: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: D:\ctms\node_modules\gifsicle
Output:
‼ read ECONNRESET
  ‼ gifsicle pre-build test failed
  i compiling from source
  × Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
```

![gifsicle](https://user-images.githubusercontent.com/2075006/74698352-6edf5e00-5238-11ea-902e-81d922d2f0e5.png)

**Comment by kohler** [comment]
This is an issue with an npm package, not Gifsicle.

**Comment by fargonmer** [comment]
What's  the issue with the npm package?

**Comment by fargonmer** [comment]
> This is an issue with an npm package, not Gifsicle.

What's the issue with the npm package?

**Comment by kohler** [comment]
I don’t know, I didn’t write the npm package, and I do not build gifsicle on windows. If an npm package fails to build Gifsicle, that issue should not be reported here.

**Comment by fargonmer** [comment]
> I don’t know, I didn’t write the npm package, and I do not build gifsicle on windows. If an npm package fails to build Gifsicle, that issue should not be reported here.

Ok. Any idea on this ?.  Warning: Error: spawn /applic/node_modules/optipng-bin/vendor/optipng

**Comment by kohler** [comment]
Again, issues with NPM should not be reported here. Any problem involving node_modules should not be reported here
