### ISSUE TITLE
Is there a JavaScript port of gifsicle ?

### ISSUE THREAD

**Issue by cuixiping** [kohler/gifsicle#157]
We can use gifsicle in web browser if there is a JavaScript port of gifsicle.

**Comment by jamsinclair** [comment]
@cuixiping Someone attempted a WASM port a while ago here: https://github.com/kohler/gifsicle/issues/148

To port an existing library to work with Web Assembly is a bit of an art form in fine-tuning and debugging. Would love to see a GIF library officially compiling down to wasm 🤞

**Comment by renzhezhilu** [comment]
[gifsicle-wasm-browser](https://github.com/renzhezhilu/gifsicle-wasm-browser)
