### ISSUE TITLE
After optimized, the gif become bigger.

### ISSUE THREAD

**Issue by qiankunxienb** [kohler/gifsicle#163]
for example, this gif:

![7b223610-4a32-4394-a3b9-68e85d7ff4fb](https://user-images.githubusercontent.com/71627005/117943985-4a8d0700-b33f-11eb-86e3-d455aa580f7f.gif)

the origin size is 9.9 MB:
![image](https://user-images.githubusercontent.com/71627005/117944039-5d074080-b33f-11eb-9478-c27a4d6a58d9.png)

After optimized, the size become 12MB:

![image](https://user-images.githubusercontent.com/71627005/117944318-b66f6f80-b33f-11eb-8be8-40cb66bac6b0.png)

**Comment by kohler** [comment]
There is no guarantee that `-O1` will actually shrink a GIF.  You can try `-O3`; that might do better; but in general gifsicle never *guarantees* to shrink a GIF file size.
