### ISSUE TITLE
Add to Ubuntu's Launchpad PPA

### ISSUE THREAD

**Issue by kubinka0505** [kohler/gifsicle#164]
I'm making a Google Colab notebook and I want to use the latest (1.92) gifsicle version, but with `apt-get install` I have only 1.91 as a latest.

I've figured out that official program versions can be bypassed by adding [PPA](https://help.ubuntu.com/stable/ubuntu-help/addremove-ppa.html.en)s (Personal Package Archive). [I've searched for it](https://launchpad.net/~ubuntu/+ppas?name_filter=gifsicle) but I couldn't find anything simple yet satisfying.

Can somebody add it please? I cannot do it myself since I never used non-NT operating systems - I don't know how to do it.

**Comment by alexmyczko** [comment]
https://packages.ubuntu.com/search?keywords=gifsicle
if you had Ubuntu 20.04 or later, you'd get the latest version...
