### ISSUE TITLE
The frame is broken when received

### ISSUE THREAD

**Issue by AnatolyArt** [kohler/gifsicle#166]
There is a gif: 
![tenor](https://user-images.githubusercontent.com/38701853/120804826-bf71ec00-c54d-11eb-9766-10b5cf655646.gif)

when I run 
`
gifsicle tenor.gif '#1' > 2_1.gif
`
I get something broken.
![2_1](https://user-images.githubusercontent.com/38701853/120804802-ba14a180-c54d-11eb-9403-29aaef2ef4a9.gif)
 For some reason, part of the picture disappears. On some gifs, everything works correctly.
What im doing wrong?

**Comment by kohler** [comment]
This is as expected. That frame uses transparency to optimize its size. Try `gifsicle -U '#1'`; the `-U` flag attempts to unoptimize.
