### ISSUE TITLE
Save multiple frames with one command

### ISSUE THREAD

**Issue by AnatolyArt** [kohler/gifsicle#167]
Is it possible to save 3 different frames to different files with one command, since the file is large, it takes a long time to call command 3 times. Perhaps one command will be faster. 
something like:
`gifsicle -U 1.gif '#3' > result.gif & '#13' > result2.gif & '#31' > result3.gif`

**Comment by AnatolyArt** [comment]
Help anyone ?

**Comment by kohler** [comment]
You can do something like this with the `--explode` option, which will save ALL frames to programmatically-determined names (like `1.gif.000`, `1.gif.001`, etc.)
