### ISSUE TITLE
Segmentation fault (core dumped) when i resize gif

### ISSUE THREAD

**Issue by ken9xkyo** [kohler/gifsicle#168]
I used: gifsicle --resize 220x140 --resize-method box --resize-colors 256 --dither --colors 256 input.gif -o output.gif
Segmentation fault (core dumped)
My gif: https://drive.google.com/file/d/1iAsUWqNRIrnFu8LtPvDkluw2H_S7iS70/view?usp=sharing

**Comment by kohler** [comment]
Thank you very much for reporting this!
