### ISSUE TITLE
[request] Ability to remove every nth frame from GIF

### ISSUE THREAD

**Issue by Majki** [kohler/gifsicle#17]
Can we get funcionality, that will delete every nth frame from existing animated gif?

Like I have a GIF consisting of 300 frames, every one with frame time 41 ms for example. I wish to be able to remove like every sixth frame, this is 6, 12, 18, and so on. That kind of operation reduces GIF size and removed frames are unlikely to be noticed. 

-parameter would give me option to set which "nth" frame I want removed.

Important is no changing framerate or anything - still i.e. 41 ms.

**Comment by rjsteinert** [comment]
Trying someone's script for me fails on macOS https://gist.github.com/aug2uag/0906c80efb9fd6067b54#gistcomment-2160040

Would be great to have this in gifsicle.
