### ISSUE TITLE
Missing index.html if running gifsicle-wasm?

### ISSUE THREAD

**Issue by PowerNow** [kohler/gifsicle#173]
Hi, I try to run gifsicle-wasm/gifsicle-react but I get an error:

My commands:
1. cd gifsicle-wasm/gifsicle-react
2. npm install -> installs the local packages in node_modules
3. npm start

Error:
```
Could not find a required file.
Name: index.html
Searched in: D:\gifsicle-wasm\gifsicle-react\public
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle-react@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
```
But there is no public folder or index.html file. What I'm doing wrong here?
Thanks...

**Comment by kohler** [comment]
This is a bug in the NPM package gifsicle-wasm and should be reported there.

**Comment by PowerNow** [comment]
Thxs! I thought to post it here because there are no issues and under descripten is the sentence:
`If you have trouble building or running Gifsicle, try GitHub issues: https://github.com/kohler/gifsicle`
I related this also to build wasm.
