### ISSUE TITLE
Artifacts / trails when trimming

### ISSUE THREAD

**Issue by MarcelRobitaille** [kohler/gifsicle#190]
I am trying to cut away the beginning of a GIF and take only the ending without affecting its quality. I tried with the command

```
gifsicle in.gif '#237-312' > out.gif
```

There are strange artifacts and trails in the result.

`in.gif`:
![Peek 2023-05-29 16-23](https://github.com/kohler/gifsicle/assets/8503756/0e922047-5992-43e2-82ca-baa3a26e22ac)
`out.gif`:
![out](https://github.com/kohler/gifsicle/assets/8503756/21c1fe47-1455-452b-89d3-17e22fae148d)

Interestingly, I get a similar result with ImageMagick:
```
convert 'in.gif[237-312]' out.gif
```

I tried compiling the latest version (bdac32963dca1b5b5134407a2034c900d576ae66) with the same result.

**Comment by jernejs** [comment]
This is not a bug – you should run `--unoptimize` first.

**Comment by MarcelRobitaille** [comment]
@jernejs That worked! Thank you. I had to recolor it first with `--colors 255` too, but now I have the desired effect.

It may not be a bug, but it's an unexpected result that I didn't see other people asking about.
