### ISSUE TITLE
trouble croping

### ISSUE THREAD

**Issue by tigros** [kohler/gifsicle#194]
Hi,

When I try to crop I get: warning: useless crop-related frame option

so the file isn't cropped.

The command I'm using is:

    gifsicle -i cute.gif -O3 --crop 648,391-1270,1079 --resize 150x150 -o cute2.gif

I thought maybe a Windows problem but Ubuntu same thing.

When I googled the error message absolutely nothing, oddly.

I've attached the file in question, any ideas?

Thanks.

[cute.zip](https://github.com/kohler/gifsicle/files/12505219/cute.zip)

**Comment by basevich** [comment]
You need to specify the frames. `"#0-"` for all frames
`gifsicle -i cute.gif -O3 --crop 648,391-1270,1079 "#0-" --resize 150x150 -o cute2.gif`
