### ISSUE TITLE
--optimize switch corrupts output

### ISSUE THREAD

**Issue by daxim** [kohler/gifsicle#31]
![side-by-side](https://cloud.githubusercontent.com/assets/104814/5202004/a1a095b2-7579-11e4-94a8-78d6480c561a.png)
This is version 1.86. Output images were created with:

    gifsicle -O1 haenau.gif > haenau-O1.gif
    gifsicle -O2 haenau.gif > haenau-O2.gif
    gifsicle -O3 haenau.gif > haenau-O3.gif

With `-O2` and higher, some pixels are wrong in the output.

Files: <https://gist.github.com/daxim/4e66de28b447a1ca851f>

**Comment by kohler** [comment]
Hey, I'd like to close this issue unless it's still active.

**Comment by daxim** [comment]
Closing. The bugs I filed on Firefox and Gwenview last year have not progressed, unfortunately.
