### ISSUE TITLE
Resize on merge

### ISSUE THREAD

**Issue by mistic100** [kohler/gifsicle#34]
Hello

is there an option to resize SOME input gifs when doing a merge ?

Example :
> **Inputs**
> * a.gif 533x300
> * b.gif 798x450
>
> **Command**
> gifsicle a.gif b.gif -o out.gif
>
> **Expected result**
> out.gif 533x300 with second part resized
>
> **Actual result**
> out.gif 798x450 with first part on top-left

Same question for more "complex" merges like
> gifsicle a.gif --replace "#10-30" b.gif "#0-20" -o out.gif

Or do I need to resize each gif before hand ?

----

It's not really a feature request just a question. But if you plan to add this possibility perhaps it could be done by adding a input index to options like resize, crop, scale, etc.

> gifsicle a.gif b.gif --resize**1** 533x_ -o out.gif

**Comment by kohler** [comment]
Sorry, no; resize is applied just before output.

**Comment by mistic100** [comment]
ok thanks for the confirmation
