### ISSUE TITLE
Corrupted gif crashes gifsicle

### ISSUE THREAD

**Issue by masom** [kohler/gifsicle#35]
Gifsicle crashes when a gif contains an invalid/corrupted frame.

A command line switch to tell gifsicle to drop corrupted frames would be awesome.

```bash
# gifsicle fail_gifsicle.gif
gifsicle:fail_gifsicle.gif:#102: read error: missing 52926 pixels of image data
gifsicle:fail_gifsicle.gif:#102: fatal error: too many missing pixels, giving up
```

ImageMagick has the same problem:
```bash
convert fail_gifsicle.gif fail.gif
convert: corrupt image `fail_gifsicle.gif' @ error/gif.c/ReadGIFImage/1355.
convert: no images defined `fail.gif' @ error/convert.c/ConvertImageCommand/3210.
```

Not including the specific frame that is corrupted works:
```convert 'fail_gifsicle.gif[0-101]' -coalesce test.gif```

Gif:
![fail_gifsicle](https://cloud.githubusercontent.com/assets/438456/6813088/392290b2-d249-11e4-9ad0-391ce9556066.gif)

```
LCDF Gifsicle 1.87
Copyright (C) 1997-2014 Eddie Kohler
This is free software; see the source for copying conditions.
There is NO warranty, not even for merchantability or fitness for a
particular purpose.
```

**Comment by masom** [comment]
Another gif with a bad last frame:
https://popkey-assets.s3.amazonaws.com/original-9d4c26e6-06bf-46bc-a1ed-e956acaa66f0.gif

**Comment by masom** [comment]
Another gif with a bad last frame:
![original-9d4c26e6-06bf-46bc-a1ed-e956acaa66f0](https://cloud.githubusercontent.com/assets/438456/6825462/2b05c8e0-d2d1-11e4-8f7d-df2a7dc60c42.gif)

**Comment by kohler** [comment]
OK. Fixed in bd093162f884856e9c13bb0fa8ac7cfd6a1ac133.

**Comment by masom** [comment]
I just built https://github.com/kohler/gifsicle/commit/bd093162f884856e9c13bb0fa8ac7cfd6a1ac133 and gifsicle still produces the following error:

```gifsicle:fail_gifsicle.gif:#102: read error: missing 52926 pixels of image data```

```gisicle --help``` does show `      --no-ignore-errors        Quit on very erroneous input GIFs.`

**Comment by kohler** [comment]
Despite the error, the GIF was still processed this time. Right?

**Comment by masom** [comment]
Oh my bad. I didn't realize the message saying the output was STDOUT on a terminal. The gif was generated properly with the warnings

Thank you!

**Comment by wanggaolin** [comment]
This error can be ignored? Then continue to convert？
