### ISSUE TITLE
Not possible to use in an offline environment

### ISSUE THREAD

**Issue by mkjaer** [kohler/gifsicle#36]
We have an offline environment with a local NPM, bower etc. repository mirror.
Some dependencies are causing issues, among those, gifsicle.

I narrowed the problem down by looking into the source and I found it has different URLs hardcoded into it.

Any chance this can be handled a different way?

**Comment by kohler** [comment]
This is crazy. Gifsicle does not access the network at all. What URLs are you talking about.

**Comment by mkjaer** [comment]
Okay. Now I am confused myself. I used npm install gifsicle, which failed because of a connection error.
Then I looked into the file and found this: https://github.com/imagemin/gifsicle-bin/blob/master/test/test.js
Which led me to http://www.lcdf.org/gifsicle/, which then led me here.

I'm sorry, I guess it's a imagemin problem.

**Comment by kohler** [comment]
No problem!
