### ISSUE TITLE
Gifs from higher-color sources?

### ISSUE THREAD

**Issue by mnutt** [kohler/gifsicle#37]
I'm looking into building gifs from 32-bit PNG frames, and I was wondering if there would be any advantage to letting gifsicle work from the higher-quality sources rather than converting to gif using my own (possibly inferior) quantizer. But it looks like Gif_Image only stores image data in uint8, so I'm just looking for some guidance on whether it's possible and worth pursuing.

**Comment by kohler** [comment]
If you are willing to change the code, the Gifsicle quantization algorithms actually can work on 24-bit colors—though it might be a lot of work. There's even a sort of example of how this might work: scale_imge_add_colors in xform.c does a kind of 24-bit-color quantization.

**Comment by mnutt** [comment]
Thanks, that's really helpful. I'll look into using the quantizer with 24-bit color images.
