### ISSUE TITLE
Assert in resize_stream() validating transparency or background values may be incorrect.

### ISSUE THREAD

**Issue by twojtasz** [kohler/gifsicle#42]
We have a build that keeps asserts enabled.  It was crashing on this image.  http://www.golftown.com/images/maps/22.gif

The root problem appears to be this line
https://github.com/kohler/gifsicle/blob/a1bf7c93a2a646178903acecda6a92d1d2fcad41/src/xform.c#L1083
Where 'gfs->images[0]->transparent' is -1, but 'gfs->global' is null, making an access violation accessing 'gfs->global->ncol'. 

the packed byte from gifread() on this image is 0x70, so no global color table.  I'm am unfortunately not familiar enough with the complete gif spec/code structure to know if this assert is accurate of not.

**Comment by kohler** [comment]
Thanks for reporting this bug. What is the exact command line you used to cause the crash? I've tried a couple with no problem.

**Comment by kohler** [comment]
OK, I think the assertion is not needed, so I removed it in da05f3a. But even with --scale arguments, and --resize-method things, I couldn't trigger the assertion.

**Comment by twojtasz** [comment]
Internally we are making a direct call to resize_stream() right after
gifread().

I did try the --resize opt with the gifsicle cmd but figured it was
compiled with NDEBUG defined.

I'll verify if that is the case on my build.

**Comment by kohler** [comment]
No, gifsicle is not compiled with NDEBUG (unless you pass CPPFLAGS=-DNDEBUG to ./configure).

So this is not a bug in gifsicle exactly, but in some fork? Hm. In future please be clear about that in the initial report and provide a specific command line to replicate the bug on gifsicle itself. I still am pretty sure the assertion's unnecessary.

**Comment by twojtasz** [comment]
Yes, I apologize for not making that clearer.  The "fork" is no different, we just are calling directly into the library not using the command line tool.

I was able to debug gifsicle itself and noticed the global color map is being defined, but not in read_gif().  I'm curious what is different between the two and will investigate on our side further.  However, If you have validated that the assert is unnecessary i consider this closed.

Thanks.

**Comment by kohler** [comment]
I can't be 100% sure the assert is unnecessary but I believe it is
unnecessary.

When you call directly into the library you may be violating invariants
that the program typically maintains. In gifsicle resize_stream is only
called after an output gif is constructed, and that construction process
creates a global colormap.

However I do think (*think*) this assert was unnecessary.
