### ISSUE TITLE
No rule to make target `@MALLOC_O@'

### ISSUE THREAD

**Issue by pornel** [kohler/gifsicle#45]
Since this commit: fe02f01e75edf7fde1238a08b86df37dbb29aecb the build fails with:

> make[2]: *** No rule to make target `@MALLOC_O@', needed by `gifsicle'.  Stop.

I'm testing on OS X 10.11

**Comment by pornel** [comment]
and if I delete MALLOC_O everywhere I'm left with undefined symbol for `fail_die_malloc`

**Comment by kohler** [comment]
I also build on Mac OS X and don't have this problem. Likely your Makefile.in did not get re-made from Makefile.am (perhaps you did not configure with --enable-maintainer-mode?). Try running `./bootstrap.sh` again.

**Comment by pornel** [comment]
`./bootstrap.sh` helped! Thanks.
