### ISSUE TITLE
Unitialized memory used as transparent color

### ISSUE THREAD

**Issue by pornel** [kohler/gifsicle#46]
in https://github.com/kohler/gifsicle/blob/66b6394a0edde6ed092bbad6bab1a975697eb64f/src/quantize.c#L1496,L1507

`Gif_Color transp_value` is not initialized if there's no `old_cm`, and then `GIF_COLOREQ(&transp_value, &new_cm->col[i])` proceeds to use potentially-garbage data.

I'm not sure what the real impact of this is, but it's allowed to summon nasal demons.

**Comment by kohler** [comment]
Thanks; addressed in 5b3813c!
