### ISSUE TITLE
GIF won't open on OS X/Safari after optimisation

### ISSUE THREAD

**Issue by jak** [kohler/gifsicle#50]
I have encountered a peculiar file which after optimisation at any level will not display on OSX or Safari.
The GIF displays perfectly fine in Chrome/Firefox/Windows however.

This is the uncompressed original.
![sale](https://cloud.githubusercontent.com/assets/191585/10097050/2a9fce7c-636e-11e5-8801-274ad20ad8ed.gif)

I looked into image dimensions, frames, number of colours all as potential issues - however I've been able to optimise others with complete success using gifsicle. I can't figure out what is different about this GIF that results in gifsicle creating a GIF that cannot be displayed on OS X.

I've tried different -O levels, and tried the --careful options with no success. I'm sorry I haven't been able to determine a cause and so this issue isn't as helpful as it should be.

**Comment by kohler** [comment]
Thanks for providing this. I have boiled it down the following one-frame, 3-color GIF, which Safari refuses to display:

![s](https://cloud.githubusercontent.com/assets/410647/10148491/dae00d3e-6601-11e5-9c8d-8e1484841169.gif)

Contrast that GIF with this one-frame, 3-color GIF, with the same data but encoded very slightly differently, which Safari does display:

![s](https://cloud.githubusercontent.com/assets/410647/10148537/11244b80-6602-11e5-8f04-37eef1aa7fb2.gif)

**Comment by kohler** [comment]
I am mystified by this problem. It seems very unlikely to be a gifsicle bug (and likely to be a Safari/Webkit bug). I tried to extract the Webkit nightly GIF parser from Safari, though, and it handles the problematic image content fine. It may, or may not, be relevant that the “broken” GIF content diverges from the “fixed” GIF content at offset 0x1101.

**Comment by kohler** [comment]
I reported the bug as a Safari/Webkit bug to the webkit.org bug tracker:

https://bugs.webkit.org/show_bug.cgi?id=149610

And the bug has been fixed in OS X 10.11. Thanks for the report!

**Comment by jak** [comment]
Hey, thank you for your help in finding and reporting the issue!
