### ISSUE TITLE
NPM 3 Install Fails

### ISSUE THREAD

**Issue by gravidThoughts** [kohler/gifsicle#51]
node v4.1.2
npm 
Windows 7 Enterprise

```
> gifsicle@3.0.1 postinstall C:\dev\Angular Testing\node_modules\gifsicle
> node lib/install.js

  ‼ Redirected 10 times. Aborting.
  ‼ gifsicle pre-build test failed
  i compiling from source
  x Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff --
prefix="C:\dev\Angular Testing\node_modules\gifsicle\vendor" --bindir="C:\dev\An
gular Testing\node_modules\gifsicle\vendor" && make install
Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by kohler** [comment]
This is not a gifsicle bug. You may report it to npm if you prefer.

**Comment by gravidThoughts** [comment]
@kohler Is it possible for gifsicle to build natively on a windows machine? My understanding is that `autoreconf` can only run in an environment like cygwin.

**Comment by kohler** [comment]
Yes, it does build on Windows; see the README.

**Comment by gravidThoughts** [comment]
@kohler Sorry, I wasn't clear, I meant build natively using npm method. If the gifsicle npm module fails to download the binary, it attempts to build locally. This will not work on a Windows machine, correct?

**Comment by kohler** [comment]
This is the repository for Gifsicle. Not the Gifsicle NPM module. I do not maintain the Gifsicle NPM module. I have nothing to do with it.
