### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [kohler/gifsicle#56]
Would you like to add the configuration script "[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/kohler/gifsicle/blob/97c07a398970f0f9fd95aa8b2d608bc6367c68db/configure.ac#L227 "Configuration checks")?

**Comment by kohler** [comment]
Why?

**Comment by elfring** [comment]
How do you think about to reuse the provided checks for better software portability?

**Comment by kohler** [comment]
I've never received a report of a portability problem.
