### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [kohler/gifsicle#57]
Would you like to replace more defines for constant values by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages) to stress their relationships?
* [KC_…](https://github.com/kohler/gifsicle/blob/97c07a398970f0f9fd95aa8b2d608bc6367c68db/src/kcolor.h#L15)
* [SCALE_METHOD_…](https://github.com/kohler/gifsicle/blob/a3898a44843ab8e52356ff14d06ee412083ba023/src/gifsicle.h#L149)

**Comment by kohler** [comment]
Not really. Thanks for your interest, but I'd prefer issues be reserved for actual issues, i.e., problems.

**Comment by elfring** [comment]
How do you think about to reduce the "problem" about convenient software debuggability?

**Comment by kohler** [comment]
If you want to open a pull request I'd welcome it and perhaps comment or accept it.
