### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [kohler/gifsicle#58]
Would you like to add more error handling for return values from functions like the following?
- [fclose](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream.") ⇒ [get_input_stream](https://github.com/kohler/gifsicle/blob/6b8043da3e4e86a837a8285c7d81a9b3f1b54bd2/src/gifview.c#L522)
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [open_giffile](https://github.com/kohler/gifsicle/blob/9c02e6bc71ca939da8e022e4335273ed151c1d1e/src/gifsicle.c#L557)

**Comment by kohler** [comment]
Why?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by kohler** [comment]
If you have a pull request please submit one.

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?
