### ISSUE TITLE
Fullscreen display for gifview?

### ISSUE THREAD

**Issue by jmwohl** [kohler/gifsicle#59]
I don't see it in the options, but for gifview is there anyway to get the gif to display full screen? I can set the geometry to the entire screen, but the gif tiles.

I'd love an option that would fit it to the screen (without stretching) and an option that would stretch it to the entire screen.

**Comment by kohler** [comment]
You can apply a gif to the desktop with the `--window` option: `--window root`. Patches are welcome; I won't be adding this option myself.

**Comment by kohler** [comment]
BTW you can use `gifsicle` to stretch an image to a given size, and then `gifview` to view it at that size
