### ISSUE TITLE
Feature req: Upscaling mode for --resize-fit

### ISSUE THREAD

**Issue by papandreou** [kohler/gifsicle#67]
(I originally posted about this on a [closed issue](https://github.com/kohler/gifsicle/issues/13#issuecomment-196321546), which is probably not the best way to be heard :)

I'm working on an image processing service that supports different engines depending on the type of the image to be processed. Gifsicle seems to be the only thing out there that doesn't screw up weird animated gifs with differently sized frames, so the idea is to use gifsicle when both the input and output formats are gif.

The most common operation that I need to support is to scale the image to fit into a bounding box, which maps fine to `--resize-fit WxH`, except when the source image is smaller, in which case it has to be scaled up (depending on a mode flag). I cannot accomplish that with gifsicle without knowing the image metadata up front, as `--resize-fit` never scales up, and `--resize-width`/`--resize-height` cannot be used together.

So how about adding support for scaling up? Sort of like *magick's `>` geometry (turns off upscaling) modifier or [sharp](https://github.com/lovell/sharp)'s `withoutEnlargement()`?

**Comment by kohler** [comment]
You want the new `--resize-touch` argument.

**Comment by papandreou** [comment]
Fantastic, thanks a bunch!
