### ISSUE TITLE
Frame selection from optimized GIF

### ISSUE THREAD

**Issue by adavidzh** [kohler/gifsicle#71]
I just did some frame selection from what I think is an already optimised animated GIF.
The result is suboptimal, the first frames having all sorts of white spots (that persist in places that do not change much):
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/TheNightOf?src=hash">#TheNightOf</a> <a href="https://twitter.com/hashtag/POR?src=hash">#POR</a> <a href="https://twitter.com/hashtag/FRA?src=hash">#FRA</a> <a href="https://twitter.com/hashtag/EURO2016?src=hash">#EURO2016</a><br>Best moment: <a href="https://twitter.com/Cristiano">@Cristiano</a> all over the <a href="https://twitter.com/FFF">@FFF</a> box limping for <a href="https://twitter.com/selecaoportugal">@selecaoportugal</a><a href="https://twitter.com/hashtag/Portugal?src=hash">#Portugal</a> <a href="https://t.co/s8uQGWZxj7">pic.twitter.com/s8uQGWZxj7</a></p>&mdash; André David (@DrAndreDavid) <a href="https://twitter.com/DrAndreDavid/status/752381292159856641">July 11, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
I naively suspect that this is due to `gifsicle` jumping directly to the first frame that is of interest and starting from there without reconstructing the scene at that point in time. I.e., starting from a compressed frame instead of a full frame.

**Comment by h3xx** [comment]
You have to use `--unoptimize` to get the full frame.

gifsicle by default will give the frame as stored verbatim in the GIF, and optimized gifs use transparency pixels to "skip" storing pixel data that is the same from the last frame of the gif.

**Comment by adavidzh** [comment]
Worked like a charm!
