### ISSUE TITLE
 incorrect escape for 8-bit characters on platforms with signed char

### ISSUE THREAD

**Issue by hpfn** [kohler/gifsicle#75]
Hi,

I received a bug report (Debian) with patches,
for version 1.86 and 1.88, about 'escape for 8-bit
characters'.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838420

I am applying the patch for 1.88 (Debian Sid).

fix-escape_1.86.patch
Index: gifsicle-1.86/src/support.c
===================================================================
--- gifsicle-1.86.orig/src/support.c
+++ gifsicle-1.86/src/support.c
@@ -310,7 +310,7 @@ safe_puts(const char *s, uint32_t len, F
        case '\v': fputs("\\v", f); break;
        case '\\': fputs("\\\\", f); break;
        case 0:	  if (len > 1) fputs("\\000", f); break;
-       default:	  fprintf(f, "\\%03o", *s); break;
+       default:	  fprintf(f, "\\%03o", *s & 0xFF); break;
       }
     }
   if (last_safe != s) {

fix-escape_1.88.patch
Index: gifsicle-1.88/src/support.c
===================================================================
--- gifsicle-1.88.orig/src/support.c
+++ gifsicle-1.88/src/support.c
@@ -311,7 +311,7 @@ safe_puts(const char *s, uint32_t len, F
        case '\v': fputs("\\v", f); break;
        case '\\': fputs("\\\\", f); break;
        case 0:    if (len > 1) fputs("\\000", f); break;
-       default:   fprintf(f, "\\%03o", *s); break;
+       default:   fprintf(f, "\\%03o", *s & 0xFF); break;
       }
     }
   if (last_safe != s) {

Regards,
Herbert

**Comment by kohler** [comment]
Thanks for this report. Fixed in 2eff5e6.
