### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by rrraikman** [kohler/gifsicle#81]
I'm trying to install gifsicle using npm and it keeps throwing the following error. I have reinstalled and updated git, node, and npm and have been exhaustively searching the web for an answer but have had no luck. Error message says it is most likely a problem with the gifsicle package and not with npm. node lib/install.js is what is failing. Trying to install on a Windows 10 virtual machine using virtualbox.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\.npm-global\\node_modules\\npm\\bin\\npm-
cli.js" "install" "gifsicle"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! gifsicle@3.0.3 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gifsicle@3.0.3 postinstall script 'node lib/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gifsicle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gifsicle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gifsicle
npm ERR! There is likely additional logging output above.

npm -v : 3.10.9
node -v : v6.9.1

**Comment by kohler** [comment]
Npm problems should not be reported here. Report the problem to the maintainer of the npm gifsicle package, which is not me. `npm bugs gifsicle` will lead you to the right place, as npm itself reported.
