### ISSUE TITLE
The problem about status code

### ISSUE THREAD

**Issue by shuaihanhungry** [kohler/gifsicle#82]
Why gifsicle exits with status 1 but I can get the expected output.gif, when I get the reports

> gifsicle: While reading 'input.gif' frame #85:
gifsicle:   warning: trailing garbage after GIF ignored

the command is
`gifsicle -k 128 --resize 122x109 input.gif > 'output.gif'`
`echo $?`

the picture is
![input](https://cloud.githubusercontent.com/assets/8935339/20961869/f0d2ffdc-bca1-11e6-93c6-ced0074cef36.gif)

**Comment by kohler** [comment]
Since there was an error, gifsicle exited with an error status. You may want the `--no-warnings` argument.
