### ISSUE TITLE
Cropping Gif in circle shape

### ISSUE THREAD

**Issue by UmaMoiseenko** [kohler/gifsicle#83]
It does not seem as if gifsicle has built in support for cropping gifs into a circle shape. Is this something that I have missed in the documentation? Thank you for your help in advance.

**Comment by kohler** [comment]
Not supported, no.

**Comment by eugenekgn** [comment]
Are you planning to add support for it?

**Comment by kohler** [comment]
No.

**Comment by eugenekgn** [comment]
ok, thanks for the fast response!

**Comment by oda1560** [comment]
:-(
