### ISSUE TITLE
 How to optimize CPU

### ISSUE THREAD

**Issue by okfirelee** [kohler/gifsicle#86]
mine linux CPU runing 100%

**Comment by okfirelee** [comment]
i want '--conserve-memory' same to run CPU

**Comment by kohler** [comment]
Do you think gifsicle is in an infinite loop? Can you post an image that you think Gifsicle is handling incorrectly?

**Comment by okfirelee** [comment]
My CPU is not enough . The system needs to run other programs. So system only runing this software. but this problem is not critical  . I need a host to run it alone.

**Comment by kohler** [comment]
This is not a gifsicle issue. Gifsicle uses however much CPU it can to get the problem solved quickly. If you want to make gifsicle run slower but take less CPU you could use the generic `nice` program.

https://en.wikipedia.org/wiki/Nice_(Unix)
