### ISSUE TITLE
Command line usage

### ISSUE THREAD

**Issue by okfirelee** [kohler/gifsicle#87]
-O3 --conserve-memory --resize-method sample --scale 1
running filesize = 4.36M

-O3 --conserve-memory --resize-method sample --scale 0.9
running filesize = 9.2M

-O3 --conserve-memory --resize-method sample --scale 0.8
running filesize = 8.4M

How to avoid this effect？

i think to run --scale 0.9 file < 4.36M

**Comment by okfirelee** [comment]
I just want to cut the size of the image with the clip but the size of the cropped image becomes larger

**Comment by kohler** [comment]
Shrinking an image will not always shrink the file size. This is inherent in compressed image technology.

There might be a bug, but you need to attach the problematic image or there is nothing I can do to verify the problem or help solve it.

If you do not start leaving useful bug reports I am going to block you.

**Comment by okfirelee** [comment]
source GIF
http://ohwfxc8wt.bkt.clouddn.com/self.gif

other narrow GIF 
http://ohwfxc8wt.bkt.clouddn.com/other.gif

gifsicle  narrow GIF 
http://ohwfxc8wt.bkt.clouddn.com/gifsicle.gif

use
-O3 --resize-method sample and --resize-fit-width

I want to reduce the warranty clarity

**Comment by kohler** [comment]
Try -O3 --resize-method mix --resize-fit-width 138 -k64 or such

This is a difficult image to shrink—it doesn't fit great with the GIF format. What is the other software?

**Comment by okfirelee** [comment]
www.piggif.com/tools/compress its online tool.
Thank you for providing a perfect way.

**Comment by okfirelee** [comment]
whats '-k64' function ? the manual is not write it

**Comment by okfirelee** [comment]
I want to compress the bulk of the picture. <1M or < 3M. I dont want to reduce clarity.Properly reduced size. Do you have any good advice?

**Comment by okfirelee** [comment]
I would like to reduce the size of the compression. Test results are not ideal. because Image will become larger after cutting

**Comment by kohler** [comment]
If piggif.com is working better for you you should use that tool.

`-k` is described in the manual.

There is not always a way to reduce an image's file size without reducing its clarity.

The options you should play with are `--resize-method`, `-O`, and `--colors` (`-k`). `--resize-colors` is a secondary option that may be useful for you.
