### ISSUE TITLE
Travis-CI is running the same build three times

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [kohler/gifsicle#92]
The intention seems to be to run:
```
CC="gcc"
CC="gcc -std=c89"
CC="clang"
```
however this is [not actually happening](https://travis-ci.org/kohler/gifsicle/builds/185284118). Looking at the clang build for example you can see
```
$ export COVERITY_SCAN_TOKEN=[secure]
$ export CC="clang"

$ export CC=gcc
$ gcc --version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

[...]

make[2]: Entering directory `/home/travis/build/kohler/gifsicle/src'
gcc -W -Wall -DHAVE_CONFIG_H -I. -I..    -I../include   -g -O2 -MT clp.o -MD -MP -MF .deps/clp.Tpo -c -o clp.o clp.c
mv -f .deps/clp.Tpo .deps/clp.Po
```

Only the standard gcc build is actually being run, unless I am totally misunderstanding how this is working.

**Comment by kohler** [comment]
Thanks! This should be addressed in 53b0944.
