### ISSUE TITLE
error message info

### ISSUE THREAD

**Issue by okfirelee** [kohler/gifsicle#93]
gif url
http://ohwfxc8wt.bkt.clouddn.com/5a612fc28364f8a2f22c0b69c243a554.gif

This image is not the same as the normal image, there are parameters damaged but can not see.
There are a lot of pictures on the Internet are like this.
I want to know why and how to deal with it

err message:
get weather api error:gifsicle:/press/5a612fc28364f8a2f22c0b69c243a554.gif:#54: read error: unknown block type 150 at file offset 1769524
gifsicle:/press/5a612fc28364f8a2f22c0b69c243a554.gif:#53: read error: image corrupted, code out of range (20 times)
gifsicle:/press/5a612fc28364f8a2f22c0b69c243a554.gif:#53: read error: (not reporting more errors)
gifsicle:/press/5a612fc28364f8a2f22c0b69c243a554.gif:#53: read error: missing 2291 pixels of image data

**Comment by kohler** [comment]
That image is corrupted, just as Gifsicle says.
