### ISSUE TITLE
It is allow remove xmp information from image?

### ISSUE THREAD

**Issue by evilebottnawi** [kohler/gifsicle#99]
I looked through all the options, but I could not find this option.

Image:
![gvjkc](https://cloud.githubusercontent.com/assets/4567934/26217159/22f9cb66-3c0f-11e7-934a-5f7bb8ecb97f.gif)

Before - 972 238 bytes
After - 971 120 bytes (`exiftool -all= image.gif`)

Useful for optimization images.

**Comment by kohler** [comment]
`--no-app-extensions` will remove this extension.

**Comment by evilebottnawi** [comment]
@kohler thanks!
